name: Build Release

on:
  workflow_dispatch:
    inputs:
      description:
        description: 'release description.'
        required: false
        type: string
jobs:
  build-and-release:
    if: |
      github.actor == github.repository_owner
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.11

      - name: Get version from package.json
        id: package-version
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build Executable
        run: bun build:executable

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/airbuddy-security
          tag_name: ${{ steps.package-version.outputs.version }}
          name: ${{ steps.package-version.outputs.version }}
          body: |
            ${{ inputs.description }}
